### ISSUE TITLE
Navigation does not update when service info is updated

### ISSUE THREAD

**Issue by juhaniaa** [juhaniaa/ja222qm-webbramverk-yoClient#1]
I have a service with a user object that gets updated when a user logs in or out:
https://github.com/juhaniaa/ja222qm-webbramverk-yoClient/blob/master/app/scripts/services/auth.service.js

This controller sets its scope variables "name" and "logged" to the value of the user objekt in the auth_service:
https://github.com/juhaniaa/ja222qm-webbramverk-yoClient/blob/master/app/scripts/controllers/navUser.js

This controller also sets it own scope variables with the same names to the same values:
https://github.com/juhaniaa/ja222qm-webbramverk-yoClient/blob/master/app/scripts/controllers/main.js

This is the main-html-template that is used for all pages, then a specific view is inserted in this one depending on route.
https://github.com/juhaniaa/ja222qm-webbramverk-yoClient/blob/master/app/index.html

This is the view-template for main/home page, when a user has logged on the "name" and "value" params are correctly set in this, but not in the navigation, which is part of the index.html template
https://github.com/juhaniaa/ja222qm-webbramverk-yoClient/blob/master/app/views/main.html

How should I register the scope/variables in the navUser controller for them to be updated when a change occurs? Should this be done with a directive, is that the only way?

**Comment by thajo** [comment]
The problem is that the navUserCtrl is loaded before the signin is happening. We must have some event that notifies that controller (or other controllers). One solution would be to use $watch to watch the Service method when it changes.

```
// in navUser - NavUserCtrl

// watch the authService.logged() - data will be be the return value (on every change)
$scope.$watch( function () { return authService.logged(); }, function (data) {
    console.log("watch");
    console.log("authService is: " +data);
  }, true);
```

More info: http://stackoverflow.com/questions/15800454/angularjs-the-correct-way-of-binding-to-a-service-properties?lq=1

Another way is to think of the Auth-service as an global module that many controllers/views can get data. I would then prefere using a brodcast-thinking as explained in this thread (second answer):
http://stackoverflow.com/questions/12576798/how-to-watch-service-variables

When the signin is success broadcast a event to the rest of the application (on rootScope) and send along the data you want

```
$rootScope.$broadcast('user:loggedin',data);
```

And in the navUserCtrl

```
$scope.$on('user:loggedin', function(event,data) {
     // you could inspect the data to see if what you care about changed, or just update your own scope
     console.log("####!### Someone has logged in...");
     console.log(data);

   });
```

**Comment by juhaniaa** [comment]
Thank you! First solution is what I was looking for but didn't know how to do. It works fine for now at least :)
